### ISSUE TITLE
Question: Asynchronicity and wrapping execute in a Promise

### ISSUE THREAD

**Issue by davout1806** [mithunsatheesh/node-rules#102]
Admittedly I'm still trying to wrap my head around js asynchronicity model. I thought I was finally getting it but apparently not.

It's seems node-rules is running asynchronously during execute using the callback. In the code there is no await/async or promise but there is a call to process.nextTick(). I thought I could wrap this into a Promise. Is this possible?

Thanks

```
const NodeRules = require('node-rules');

class RulesEngine {
  
  constructor(rules, options) {
    this.engine = new NodeRules(rules, options)
  }

  execute(fact) {
    const thisHolder = this
    return new Promise((function(resolve) {
      thisHolder.engine.execute(fact, resolve)
    }))
  }
}
```

**Comment by mithunsatheesh** [comment]
Can you please create a jsfiiddle/runkit example and post here? From the above sample, I do not see a concern in using Promises or async/await.

**Comment by davout1806** [comment]
Apologies. I had an extra await in my call chain which was causing it to loop continuously without getting a response.

Works like a charm.

[https://runkit.com/davout1806/604b4fd61f62450019201864](https://runkit.com/davout1806/604b4fd61f62450019201864)
