### ISSUE TITLE
Delete unneeded merged branches?

### ISSUE THREAD

**Issue by OmgImAlexis** [mithunsatheesh/node-rules#110]
Are any of these still need? Seems they were all merged and possibly forgotten about.

https://github.com/mithunsatheesh/node-rules/tree/mi04-patch-1
https://github.com/mithunsatheesh/node-rules/tree/feature-internal-functions
https://github.com/mithunsatheesh/node-rules/tree/feature-sync
https://github.com/mithunsatheesh/node-rules/tree/hotfix-multiple-consequence-execution
https://github.com/mithunsatheesh/node-rules/tree/dev

**Comment by OmgImAlexis** [comment]
@mithunsatheesh am I good to remove the branches above?

**Comment by mithunsatheesh** [comment]
@OmgImAlexis we can remove them.

**Comment by mithunsatheesh** [comment]
completed.
