### ISSUE TITLE
Error running basic example - Cannot find module 'lodash.isequal'

### ISSUE THREAD

**Issue by Johnny-AM** [mithunsatheesh/node-rules#113]
I'll walk you through what I tried =>
1- Created an empty folder.
2- Opened the directory in the terminal and ran npm install node-rules
3- Created a new js file called noderules.js
4- Ran node noderules.js on the terminal and got the following error:
![Screenshot (187)_LI](https://user-images.githubusercontent.com/67067569/126674138-e08e3418-8f7b-488d-81da-a9d29093d8af.jpg)

Additional info:
I have the latest node and npm version.
I tried installing lodash but the error remained.
I tried deleting node_modules and running npm install but still got the same error when node noderules.js is run.
The contents of noderules.js are the same as node-rules/docs/Examples.md in the Github repo.

**Comment by mithunsatheesh** [comment]
can you mention the package version of node rules checked out?

**Comment by Johnny-AM** [comment]
> can you mention the package version of node rules checked out?

This is my node_modules file:
{
  "dependencies": {
    "lodash": "^4.17.21",
    "node-rules": "^7.0.0"
  }
}

**Comment by mithunsatheesh** [comment]
please share content of noderules.js to debug further.

**Comment by mithunsatheesh** [comment]
thanks able to repro it.

**Comment by mithunsatheesh** [comment]
Seems to be broken from 7.0.0 when lodash dependencies were moved as dev dependencies. Please use versions on 6 until we release a fix for this.

**Comment by Johnny-AM** [comment]
> Seems to be broken from 7.0.0 when lodash dependencies were moved as dev dependencies. Please use versions on 6 until we release a fix for this.

Using version 6.3 worked. 👍

**Comment by mithunsatheesh** [comment]
Thanks @Johnny-AM . Please consider checking out the latest release node-rules@7.1.0 which should also work.
