### ISSUE TITLE
Cache issue when multiple request 

### ISSUE THREAD

**Issue by anoopgcmz** [mithunsatheesh/node-rules#125]
we are sending a back-to-back request to a promise-based rule engine function. But at some point, the input value s not updating. I believe it is a cache issue.

` let rule = [{"condition": function (R) {
				R.when(options.val1 > options.val2);
			},
			"consequence": function (R) {
				this.result = false;
				this.reason = "val1 is Higher than the Limit, FraudScore: " +options.fraudScore;
				R.stop();//stop if matched. no need to process next rule.
			}
		}];
		R.register(rule);
		return new Promise((resolve, reject)=> {
			R.execute(options, function (data) {
				if (data.result) {
					resolve(Object.assign({"data" : "val2 Lesser than the Limit"}, false));
				} else {
					resolve(Object.assign({ "data" :  data.reason }, true));
				}
			});
		}); `

**Expected behavior**
Should return response according to the input by comparing numbers

**Comment by mithunsatheesh** [comment]
Please try to create a repo using runkit or jsfiddle and attach here. Else add a test case that fails. Its impossible to assume your code without seeing the entire flow.

**Comment by anoopgcmz** [comment]
@mithunsatheesh is there any cache-clearing flag in rule Engine

**Comment by mithunsatheesh** [comment]
As already mentioned please post a reproable code or write a test case.

**Comment by anoopgcmz** [comment]
instead of using options.val1 inside R.when it should be this.val1.
