### ISSUE TITLE
Export types for Typescript

### ISSUE THREAD

**Issue by alverdal** [mithunsatheesh/node-rules#135]
**Is your feature request related to a problem? Please describe.**
Typescript types are not exported and we're forced to use any type for API and Rule when defining rules.

**Describe the solution you'd like**
Export the types in lib/types.ts so that we can use these types when defining our rules.

**Additional context**
<img width="975" alt="image" src="https://user-images.githubusercontent.com/6637078/236876360-20525984-3aa1-4284-93c3-e16aeef91a5a.png">

**Comment by nikollatesla** [comment]
Thanks for pointing out? Can you raise a pull request with the suggested change and  add additional unit tests to cover this? Thanks for the help.

**Comment by alverdal** [comment]
No need to export these. My bad.
