### ISSUE TITLE
Wiki - Export/Import page is missing

### ISSUE THREAD

**Issue by ddenev** [mithunsatheesh/node-rules#136]
**Describe the bug**
The Export/Import page in wiki is missing - https://github.com/mithunsatheesh/node-rules/wiki/Exporting-and-Importing-Rules

**To Reproduce**
1. Go to wiki and click on "Export/Import Rules" link

**Expected behavior**
Page is existing

**Comment by nikollatesla** [comment]
Support for import export was removed from version 4 onwards since the apis exposed some security vulnarabilities with eval. The wiki home seems stale which is fixed in the commit.
