### ISSUE TITLE
npm ERR! tar.unpack untar error on Windows

### ISSUE THREAD

**Issue by lmayorga1980** [mithunsatheesh/node-rules#32]
**NodeJs** : 0.12.2
**Npm** : 2.7.4

```
npm ERR! tar.unpack untar error C:\Users\lmo0\AppData\Roaming\npm-cache\node-rules\3.0.2\package.tgz
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js"
"-g" "install" "node-rules"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! path C:\Users\<User>\AppData\Roaming\npm\node_modules\node-rules
npm ERR! code EEXIST
npm ERR! errno -4075

npm ERR! EEXIST, mkdir 'C:\Users\<User>\AppData\Roaming\npm\node_modules\node-rules'
File exists: C:\Users\lmo0\AppData\Roaming\npm\node_modules\node-rules
Move it away, and try again.

npm ERR! Please include the following file with any support request:
npm ERR!     Z:\lmo0\git\puppet\puppet-test\npm-debug.log
```

**Comment by munimkazia** [comment]
As the error log says, it is trying to untar an archive but a directory already exists. Remove `C:\Users\lmo0\AppData\Roaming\npm\node_modules\node-rules` and try.

**Comment by lmayorga1980** [comment]
I believe the package.tgz comes with an "/" file inside of it which make it fail. 

![screen shot 2015-04-14 at 10 15 10 am](https://cloud.githubusercontent.com/assets/3172378/7140199/a74896c6-e28f-11e4-9f2e-9bd39c0edb8b.png)

**Comment by pmclean1964** [comment]
I have the same problem. Removing the directory does nothing. Clearing NPM cache didn't work either.

**Comment by munimkazia** [comment]
This looks like an issue with NPM rather than this module. Try clearing the cache, and updating to the latest version of npm.

**Comment by pmclean1964** [comment]
Perhaps. I've cleared the cache, updated to NPM v2.7.4 and Node 12.2. Node-Rules directory is never created... directory is created in npm-cache but the install fails prior to creation of the directory... I'll look into similar issues on the web.

**Comment by pmclean1964** [comment]
sorry the Node version is 0.12.2

**Comment by lmayorga1980** [comment]
Well, 

I believe when you install the module directly from the github URL then everything works fine.

@pmclean1964 try the github URL and check if that works. 

```
npm -g install https://github.com/mithunsatheesh/node-rules/tarball/master
npm WARN excluding symbolic link node_modules\.bin\_mocha -> ../mocha/bin/_mocha
npm WARN excluding symbolic link node_modules\.bin\mocha -> ../mocha/bin/mocha
npm WARN excluding symbolic link node_modules\mocha\node_modules\.bin\jade -> ../jade/bin/jade
npm WARN excluding symbolic link node_modules\.bin\_mocha -> ../mocha/bin/_mocha
npm WARN excluding symbolic link node_modules\.bin\mocha -> ../mocha/bin/mocha
npm WARN excluding symbolic link node_modules\mocha\node_modules\.bin\jade -> ../jade/bin/jade
node-rules@3.0.2 C:\Users\<User>\AppData\Roaming\npm\node_modules\node-rules
```

**Comment by pmclean1964** [comment]
That worked! No issues!

**Comment by zl79860273** [comment]
I also met the same problem,Don't know how to solve???  help
