### ISSUE TITLE
Install failed for the release 3.0.2 on Windows

### ISSUE THREAD

**Issue by malys** [mithunsatheesh/node-rules#33]
Hi,
Your module is very interesting and I would try to use it.

But,I will try to install the last release and 

``` bash
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "node-rules@3.0.2"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path D:\Developpement\workspaces\webUI\gitAlert\node_modules\node-rules
npm ERR! code EEXIST
npm ERR! errno -4075

npm ERR! EEXIST, mkdir 'D:\Developpement\workspaces\webUI\gitAlert\node_modules\node-rules'
File exists: D:\Developpement\workspaces\webUI\gitAlert\node_modules\node-rules
Move it away, and try again.
```

I have to downgrade and use the release 3.0.1.

**Comment by mithunsatheesh** [comment]
Hi @malys ,

Need to find a Windows machine to replicate. !
Please wait as we will get back to you in some time.

Regards,
Mithun Satheesh

**Comment by malys** [comment]
For testing, https://www.modern.ie/en-us

**Comment by delaneyj** [comment]
I can confirm this for Windoes 8.1.  From a fresh directory with just an `npm init, npm install --save node-rules`

**Comment by muhammadfaizan** [comment]
is this fixed?

**Comment by mithunsatheesh** [comment]
Can find this functional on the windows OS. checked on Windows 7. Please add the exact platform details if able to reproduce now as well.

**Comment by muhammadfaizan** [comment]
@mithunsatheesh  was trying it on Windows 10

**Comment by mithunsatheesh** [comment]
There is a latest release out - 4.0.0 can you try to reproduce this now please?

**Comment by muhammadfaizan** [comment]
@mithunsatheesh  I will try to, for sure. Give me a little time.
