### ISSUE TITLE
Modify fact in consequences

### ISSUE THREAD

**Issue by frauss** [mithunsatheesh/node-rules#35]
Thanks for the much needed module.

I'm wondering if it's possible to modify the fact object inside of the consequences function?

If so, how do would you get at the modified fact in the execute callback?

Here's a sample rule where I want to modify a field on the fact based on the test:

	{
		name: "Source Test",
		condition: function(R) {
			R.when(this.Title === "STF" && this.Credit === "Noble Source")
		},
		consequence: function(R) {
			this.Caption = this.Caption + ". Noble Staffer found!";
			R.next()
		}
	}

Thanks,
Fred

**Comment by mithunsatheesh** [comment]
In the execute callback, the first paramter points to the fact only.

    R.execute(fact,function(result){
        if(result.result)
            console.log(result);// is fact with a result attribute attached to it
        else
            console.log(result);
    });

**Comment by mithunsatheesh** [comment]
Please comment back or reopen this issue if you have further questions!
