### ISSUE TITLE
Logic AND/OR between Rules

### ISSUE THREAD

**Issue by whitef0x0** [mithunsatheesh/node-rules#40]
Is it possible to add AND/OR the this.result results between rules for a given fact?

Right now I'm doing this myself but its a bit messy using nested if statements in each Rule's "consequence" function

**Comment by jaulz** [comment]
This would be interesting to know :+1: 
@whitef0x0 how do you implement the AND and OR currently?

**Comment by whitef0x0** [comment]
@mithunsatheesh

**Comment by mithunsatheesh** [comment]
Hey @whitef0x0 ,

If you can detail more about how you implemented the AND/OR combinations, it would help if we can incorporate it in the rule engine in further versions. Right now it looks to me like the conditions and consequences are flexible enough to implement any logic required.

**Comment by mendaXXXX** [comment]
Closing since there is no response.
