### ISSUE TITLE
Catching exceptions in consequence/conditions

### ISSUE THREAD

**Issue by frauss** [mithunsatheesh/node-rules#41]
Is there a way to catch errors when the consequence/condition functions are called. I've modified the execute() method where it calls these functions as follows:

```
                        var _consequence = _rules[x].consequence;
                        process.nextTick(function() {
                            try {
                                _consequence.call(session, API);
                            }
                            catch (err) {
                                callback(err, session);
                            }
                        });
```

I've also modified the callback signature to take an error parameter but I'm not sure it is as simple as it seems?

**Comment by mithunsatheesh** [comment]
I dont think this is a valid issue. You have the condition and consequence functions to put try catches if there is buggy code being introduce. We should not be introducing it into the rule engine.

**Comment by frauss** [comment]
My primary motivation is to be able to report back to the caller any errors that have occurred inside condition/consequence functions. 

We have created a simple user interface for creating rules that allows the user to create simple rule cases and in the case of more elaborate ones simply enter the function body for the condition or consequence. My concern is there could be issues with the entered code as well as what is generated from the UI representation that I want to catch at the execute() level rather than inside the specific rule.

**Comment by moshewe** [comment]
Why not put the error in the result object?

**Comment by mendaXXXX** [comment]
I don't think this is a valid issue. You have the condition and consequence functions to put try catches if there is uncertain code being introduced. We should not be introducing it into the rule engine.
