### ISSUE TITLE
Register function

### ISSUE THREAD

**Issue by hestef00** [mithunsatheesh/node-rules#42]
There is an error in the "register" function: the condition of "if" (if (rules instanceof Array)) does not work so you must change it to "if (Array.isArray(rules))".

Hence, now, the register function looks like:

```
 RuleEngine.prototype.register = function(rules) {
    if (Array.isArray(rules)) {
        this.rules = this.rules.concat(rules);
    } else if (rules !== null && typeof(rules) == "object") {
        this.rules.push(rules);
    }
    this.sync();
};
```

**Comment by mithunsatheesh** [comment]
Hi @hestef00, would you be able to share a code sample where the later breaks? AFAIK both checks perform right. Please reopen this issue with a code sample or a sample test case which would cover the use case you failed to mention in the issue.
