### ISSUE TITLE
Store functions as objects containing string representation and function object

### ISSUE THREAD

**Issue by moshewe** [mithunsatheesh/node-rules#44]
The mixing of function definitions in the JSON specification of rules and such is a real pain, also for debugging. I can imagine a "debug" running mode where the functions are eval-ed from their string representations every time so yield meaningful errors and such.

I'm just starting to work with this great library, and that just made me cringe... Is this a change you are willing to consider?

**Comment by bassdeveloper** [comment]
@moshewe , I have written a function for reading and storing these rules. I wish to integrate the functions. Any idea how I can proceed?

**Comment by mithunsatheesh** [comment]
Thanks for the feedback. Please consider raising a PR incase you have any improvements in this direction. Closing since this seems to be open for a very long time.
