### ISSUE TITLE
Breaks when using ES6 - "this" is no longe referencing the fact within condition or consequence

### ISSUE THREAD

**Issue by damianofusco** [mithunsatheesh/node-rules#48]
Breaks when using ES6 - "this" is no longe referencing the fact within condition or consequence:

// this breaks and this is an empty object in my case
condition: (R) => {
    console.log('this', this); // prints {}
}

// this of course works and this contains my fact
condition: function(R)  {
    console.log('this', this); // prints the fact
}

**Comment by mattbishop** [comment]
+1

**Comment by xaricx** [comment]
+1

**Comment by daxiang28** [comment]
For some reason, the NPM version isn't in sync with the master branch here. The fix from @jaymaycry works. Just install it like so: `npm install git://github.com/mithunsatheesh/node-rules.git#master --save`

**Comment by mmcgarr** [comment]
Has this been updated on npm yet? I still can't seem to use arrow functions with the latest release (3.1.0).

**Comment by mendaXXXX** [comment]
Its not possible since we cannot rebind an arrow function. Let us know if you have any alternate thoughts on improving the syntax.

From the Spec:

> Any reference to arguments, super, this, or new.target within an ArrowFunction must resolve to a binding in a lexically enclosing environment. Typically this will be the Function Environment of an immediately enclosing function.

http://www.ecma-international.org/ecma-262/6.0/#sec-arrow-function-definitions-runtime-semantics-evaluation
