### ISSUE TITLE
How to use node-rules with questions?

### ISSUE THREAD

**Issue by funkyremi** [mithunsatheesh/node-rules#51]
Hello,
I would like to develop an akinator/20q like application. I have some objects with caracteristics. After some auto selected questions (yes/no/don't know), the application will choose the best object according to user answers.
Is node-rules a good solution to do that? Should I use a decision tree library instead? I to s there a way to cover all possible questions?
Thank you :-)

**Comment by mithunsatheesh** [comment]
Whether akinator/20q like application can be built out of a rule engine is a generic question and not related to the functionality of this rule engine. Resolving as irrelevant issue.
