### ISSUE TITLE
Equality condition does not work in Rules engine

### ISSUE THREAD

**Issue by VenkateshSrini** [mithunsatheesh/node-rules#53]
I changed the rule in the samepleRule.js such that it is now using the "===" in rules. After that the rules is not getting evaluated properly. The changed file is attached here with. Could any of you help with the same. 

**PS**
The same below code is also attached as text file for easy execution and clarity

[simpleRule - Copy.txt](https://github.com/mithunsatheesh/node-rules/files/493136/simpleRule.-.Copy.txt)

**Comment by neoadventist** [comment]
@VenkateshSrini Hey man, maybe because you're setting it to only act when `this.transactionTotal == 500`. Did you want `this.transactionTotal < 500`?

**Comment by VenkateshSrini** [comment]
No, the inputs are correct. It is just === does not seem to work

**Comment by mithunsatheesh** [comment]
Please share the completely functional code sample if you need us to look into this issue. Currently the description does not contain enough information to qualify it as a bug.
