### ISSUE TITLE
Can I run many RuleEngine with different rules at the same time?

### ISSUE THREAD

**Issue by jackiekhuu-work** [mithunsatheesh/node-rules#57]
Please help, Let says:
- I have many facts.
- With every fact, I would like to run a rule engine with a different set of rules.
- the rule engine for every fact could be run at the same time.
--> Can I do that with node-rules (many instances of ruleEngine at a same time)?

**Comment by mithunsatheesh** [comment]
Answering the question title, instantiate multiple instances and register different set of rules. That would solve the problem you are mentioning.
