### ISSUE TITLE
Creating dynamic rule object with nested rules

### ISSUE THREAD

**Issue by nrjmr432** [mithunsatheesh/node-rules#62]
In my case i have an interface where various entities can set rules , hence there is no static set of rules which can be written on my codebase. i have to create them dynamically.But i have problems in creating nested rule objects where i have to validate if else tree scenarious with consequences for every test cases

**Comment by mithunsatheesh** [comment]
This usecase is not something that is supported by the library now. Resolving this as wont fix.
