### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by mgurnani** [mithunsatheesh/node-rules#75]
Hello,

Thanks for creating a great library !!
I would like to use it with a Typescript project. Do you have any Type definition files which can be used?

**Comment by elecompte60** [comment]
+1
I would like to have Typescript definitions for this library also.

**Comment by Riise** [comment]
+1 for a TypeScript definitions file for this library.

**Comment by LouisInFlow** [comment]
@mithunsatheesh Would you merge community generated TypeScript type declarations? Or is this something you'd like to work on yourself.

**Comment by mithunsatheesh** [comment]
@LouisInFlow Would love contributions in this direction. Please feel free to raise a pull request.

**Comment by OmgImAlexis** [comment]
I've refactored this lib to use typescript with that comes types. Some are still set to `any` as I wasn't 100% sure on all of them but this should help the library get in the right direction.

https://github.com/OmgImAlexis/node-rules

To try this until it's merged use `npm i github:omgimalexis/node-rules`.

**Comment by OmgImAlexis** [comment]
For those following we're just finishing up the changes to the `8.0.0` branch and then it should be good for release. 😄 

https://github.com/mithunsatheesh/node-rules/pull/109

**Comment by mithunsatheesh** [comment]
Thanks @OmgImAlexis for the fast turn around! Really great job on this.

**Comment by ErikBavenstrand** [comment]
How is the typescript support and 8.0.0 release coming along?

**Comment by nsingh2510** [comment]
Are we expecting it to be release this month? @mithunsatheesh  @OmgImAlexis

**Comment by OmgImAlexis** [comment]
@nsingh2510 yes. :+1:

**Comment by ammerzon** [comment]
Any updates on this?

**Comment by younes-io** [comment]
I would like to use this library, but I don't know about TS support...
Any updates on this please?

**Comment by ilveann** [comment]
Hi @mithunsatheesh
Can we help somehow to publish the 8.0.0 version to the NPM registry?

**Comment by mithunsatheesh** [comment]
Really caught up with work. Will provide an update by 12/4.

**Comment by mithunsatheesh** [comment]
Currently published in 9.0.0 branch. Took time since the compatibility with browser based builds need to be retained.

You can install it on npm via 

    npm install — save node-rules@beta.
