### ISSUE TITLE
Example code is not working my environment

### ISSUE THREAD

**Issue by uasaigoli** [mithunsatheesh/node-rules#77]
I have trying to run example listed in https://github.com/mithunsatheesh/node-rules and getting following response, and not sure what may be missing. I am getting response "Valid transaction" instead of "The transaction was blocked as it was less than 500". I did not change any data in the "fact". The fact that first line in the response is empty {}, I feel data is not going into the RuleEngine and Rule.  It could be issue with my environment but I could not nail it down. 
Any help or pointer is much appreciated.

{}
{ name: 'user4',
  application: 'MOB2',
  transactionTotal: 400,
  cardType: 'Credit Card',
  result: true,
  matchPath: [] }
Valid transaction

**Comment by mithunsatheesh** [comment]
We do not encourage questions like "why my code doesn't work". Please try to come up with an example via node runkit which explains the issue with the library. Else I would suggest asking this on a crowd debugging platform.
