### ISSUE TITLE
Question : Is this actively maintained

### ISSUE THREAD

**Issue by nitinsh99** [mithunsatheesh/node-rules#78]
Hi, thanks for the great library. I am planning to use this in my project and was wondering if this is actively maintained by you? Are there any plans to improve upon the APIs and add new features (for example I think it would be great to have a executeAll function that can run the the batch jobs against multiple facts and maybe asynchronously). Let me know if you are open to accepting PRs as well. Thanks

**Comment by mithunsatheesh** [comment]
Please open an issue describing the api thats absent and the value add. It would be great if you could explain it via a sample code. 

To answer this question. This repo is maintained. You can fork this and send out a pull request if willing to contribute too.
