### ISSUE TITLE
This package does not implement RETE algorithm

### ISSUE THREAD

**Issue by raphaeljolivet** [mithunsatheesh/node-rules#81]
This package is tagged with **RETE** on [npm](https://www.npmjs.com/package/node-rules).
However, looking at the code, it does not seems to implement the RETE algorithm.
Please remove this tag : it is misleading.

**Comment by mithunsatheesh** [comment]
Please add more details, references to make your concern clear. Providing reference materials to support the claims made and supporting explanations would help.
