### ISSUE TITLE
Rules executing twice when condition has a string search in List

### ISSUE THREAD

**Issue by payadav** [mithunsatheesh/node-rules#82]
I am using npm-rules for building an API sequentially executing set of different rules.
One of the rule has conditional evaluation of List containing a string. i.e.
{
		"id": "corule",
		"priority": 3,
		"condition": function(R){
			console.log("Executing : Co Rule Condition");
			R.when(['af','pk','sg','kt'].indexOf(this.wmdco) > -1);		
		},
		"consequence": function(R){	
                 console.log("Executing : Co Rule Consequence");	
		 R.next();
		}
    };

Everytime this rule is unexpectedly executing twice.

Log 👍 
Executing : Co Rule Condition
Executing : Co Rule Consequence
Executing : Co Rule Condition
Executing : Co Rule Consequence

What could be the possible issue here ?

**Comment by mithunsatheesh** [comment]
Use [runkit](https://npm.runkit.com/node-rules) and create a sample and post it over here. Please reopen the issue once thats done.

**Comment by payadav** [comment]
var RulesEngine = require("node-rules")

var rulesEngine = new RulesEngine();
var count=5;
var Rules =[
	{
		"id": "corule",
		"priority": 2,
		"condition": function(R){
			R.when(['af','pk','sg'].indexOf(this.co) > -1);
		},
		"consequence": function(R){
            this.se = "HIGH";		
			R.next();
		}
    },
    {
        "id": "xyzrule",
		"priority": 1,
		"condition": function(R){
			R.when(count == 5);
		},
		"consequence": function(R){
            console.log("xyzRule");
			R.stop();
		}
    }];
    rulesEngine.register(Rules);
    var fact = {
		id: "1",
		submitterco: "wmco",
		submitterem: "larry",
		coy: "bing",
		co: "af"
    };
    
    rulesEngine.execute(fact, function(data){
        if(data.se != 'H') data.se = "L";
        
        console.log(data);
    });
    
Here Co is matched in Rules at the first index of the list, however it still executes the rule second time.
