### ISSUE TITLE
Data returned in rulesengine.execute callback function is not visible outside

### ISSUE THREAD

**Issue by payadav** [mithunsatheesh/node-rules#83]
Hello,

I am not able to see or set Data returned in the callback function of rulesengine execute function. Idea is to execute Rules for multiple records (loop) and build resultset from the data received in the callback function. I have tried using await, promises but it is not working. 

Would you suggest any way out for this ?

Below is the code where i am trying to set Temp var inside RulesEngine.execute's callback function but it is always coming undefined irrespective of await or promises (if implemented)

**var  NodeRules = require('node-rules');
const RuleEngine = new NodeRules();
const RuleOne =  
	{
			"id": "ruleone",
			"condition": function(R){
				R.when(this.nume == "1");
			},
			"consequence": function(R){
                this.sev = "HIGH";
				R.stop();
			}
        };
   RuleEngine.ignoreFactChanges = true;
   
   RuleEngine.register(RuleOne);
    
   var fact = {nume: "1", comment:"xyz Comment"};
    
   let temp = "";
   await RuleEngine.execute(fact, function(data){
   console.log(data);
       if(data.sev == "HIGH")
           console.log("Sev attribut is HIGH");  
       else
           console.log("Sev attribute is LOW");
            
        temp = data;
    });**
 
   **console.log("Below Temp is not setting in the callback function of execute Rule");
   console.log(temp);**
    
Appreciate your suggestion.

**Comment by mithunsatheesh** [comment]
Please format the code and resubmit with clear explanation of whats wrong from the library. Your questions seems more to understand how await works in JS.

**Comment by payadav** [comment]
It is more about the visibility of data returned after execution of Rules on Fact object. In your library callback function of Execute is not resolving Data object visibility outside its scope. 

You seems to be in HURRY !! of resolving a ticket rather having dialogue for seeking more information.

Thanks !!

**Comment by mithunsatheesh** [comment]
payadav@ no hurry at all. How about doing the below:

1. Learn how to format code in markdown and indent properly so that the above code you shared is understandable by people.
2. Execute is a callback and resolving the variables to outside its scope is perfectly in the hand of the customer of this package since you implement the code to be put in the callback. Hence the question, is it a question on why your code doesn't work or a fault in the library?
